version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - '5432:5432'
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
