# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dev-for-apps-Eqbis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://devforapps.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a62a333237464004a0428b940f2d7108 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1213a271c11744288a22061c9e45e091 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: devforapps.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a62a333237464004a0428b940f2d7108 }}/devforappseqbis-img:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dev-for-apps-Eqbis'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_89cf21a2a4ee44519f9cb606db292968 }}
        images: 'devforapps.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a62a333237464004a0428b940f2d7108 }}/devforappseqbis-img:${{ github.sha }}'